package com.autwit.copilot.run;

import java.util.List;
import java.util.Map;
import java.util.UUID;

import com.autwit.copilot.session.SessionService;
import com.autwit.copilot.support.AbstractPostgresIT;
import com.autwit.copilot.support.RunFixtures;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ActiveProfiles;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * BUILD_BRIEF step 3's done-when: "fixture run persists 9 artifacts + snapshot".
 *
 * <p>Drives the worker one poll at a time. worker-concurrency=0 means the bean exists
 * but starts no background loops, so each test executes exactly the run it enqueued
 * rather than racing four pollers.
 */
@ActiveProfiles("all")
@org.springframework.test.context.TestPropertySource(properties = "autwit.run.worker-concurrency=0")
class FixtureRunTest extends AbstractPostgresIT {

    @Autowired
    private RunWorker worker;
    @Autowired
    private RunEnqueuer enqueuer;
    @Autowired
    private SessionService sessions;
    @Autowired
    private RunFixtures fixtures;
    @Autowired
    private RunRepository runs;
    @Autowired
    private JdbcTemplate jdbc;

    private UUID sessionId;

    @BeforeEach
    void setUp() {
        fixtures.clearQueue();
        sessionId = fixtures.newSession();
    }

    @Test
    void aFixtureRunPersistsNineArtifactsAndASnapshot() {
        var accepted = enqueuer.enqueueMessage(sessionId, "I created order XXXX",
                Map.of("order_id", "XXXX"), null, null);

        assertThat(accepted.run().status()).isEqualTo("queued");
        assertThat(accepted.run().maxAttempts()).as("invoke is never auto-retried (ADR-001)").isEqualTo(1);

        assertThat(worker.pollOnce()).isTrue();

        var run = runs.find(accepted.run().runId()).orElseThrow();
        assertThat(run.status()).isEqualTo("succeeded");
        assertThat(run.resultSummary()).containsEntry("artifacts", 9);

        assertThat(count("artifact")).isEqualTo(9);
        assertThat(count("snapshot")).isEqualTo(1);

        // part_key stability is what makes comparison a key-wise join.
        assertThat(jdbc.queryForList("""
                select sp.part_key from autwit.snapshot_part sp
                join autwit.snapshot s on s.snapshot_id = sp.snapshot_id
                where s.session_id = ? order by sp.part_key
                """, String.class, sessionId))
                .hasSize(9)
                .contains("oms.orders", "oms.order_items", "shipment.legs");
    }

    @Test
    void everyArtifactsHashIsVerifiedOnTheWayIn() {
        enqueuer.enqueueMessage(sessionId, "I created order XXXX", null, null, null);
        worker.pollOnce();

        // The fixtures carry hashes generated by an independent Python implementation of
        // the canonical form. That they all survive persist() means our Java agrees with
        // it -- which is the cross-language check CONTRACT_RATIFICATION_REQUEST.md Q1 asks
        // the orchestrator session to make on their side.
        assertThat(jdbc.queryForList(
                "select content_hash from autwit.artifact where session_id = ?", String.class, sessionId))
                .hasSize(9)
                .allSatisfy(h -> assertThat(h).startsWith("sha256:"));
    }

    @Test
    void subjectsDiscoveredAreMergedIntoTheSession() {
        enqueuer.enqueueMessage(sessionId, "I created order XXXX", Map.of("order_id", "XXXX"), null, null);
        worker.pollOnce();

        // How a shipment id found during snapshot capture becomes searchable later.
        assertThat(sessions.get(sessionId).subjects())
                .containsEntry("order_id", "XXXX")
                .containsEntry("shipment_id", "SHP-99");
    }

    @Test
    void notesArePersistedAsAnalysisSteps() {
        enqueuer.enqueueMessage(sessionId, "I created order XXXX", null, null, null);
        worker.pollOnce();

        assertThat(jdbc.queryForList(
                "select label from autwit.step where session_id = ? and kind = 'analysis'",
                String.class, sessionId))
                .singleElement(org.assertj.core.api.InstanceOfAssertFactories.STRING)
                .contains("Captured 9 tables");
    }

    @Test
    void theStepFlipsToSucceededSoThePendingCardResolves() {
        var accepted = enqueuer.enqueueMessage(sessionId, "I created order XXXX", null, null, null);
        worker.pollOnce();

        assertThat(jdbc.queryForObject("select status from autwit.step where step_id = ?",
                String.class, accepted.run().stepId()))
                .isEqualTo("succeeded");
    }

    @Test
    void aMilestoneRunCompletesTheMilestoneAndItsSnapshot() {
        var accepted = enqueuer.enqueueMilestone(sessionId, "order_created", List.of("order_flow"),
                true, "first checkpoint", null);

        // Created immediately in pending -- the UI shows it before capture finishes.
        assertThat(jdbc.queryForObject("select status from autwit.milestone where milestone_id = ?",
                String.class, accepted.milestoneId())).isEqualTo("pending");
        assertThat(accepted.run().maxAttempts()).as("snapshot.capture is side_effects: none").isEqualTo(2);

        worker.pollOnce();

        var milestone = jdbc.queryForMap(
                "select status, snapshot_id from autwit.milestone where milestone_id = ?",
                accepted.milestoneId());
        assertThat(milestone).containsEntry("status", "complete");
        assertThat(milestone.get("snapshot_id")).isNotNull();
    }

    @Test
    void aPartialCaptureMarksTheSnapshotPartialAndRaisesAFinding() {
        var accepted = enqueuer.enqueueMilestone(sessionId, "partial_capture", List.of("order_flow"),
                true, null, null);
        // The fixture routes on the message the enqueuer builds: "Mark milestone partial_capture".
        worker.pollOnce();

        // §5: partial -> snapshot partial, run SUCCEEDED, finding raised. Never silent.
        assertThat(runs.find(accepted.run().runId()).orElseThrow().status()).isEqualTo("succeeded");
        assertThat(jdbc.queryForObject(
                "select status from autwit.snapshot where session_id = ?", String.class, sessionId))
                .isEqualTo("partial");
        assertThat(jdbc.queryForObject("select status from autwit.milestone where milestone_id = ?",
                String.class, accepted.milestoneId())).isEqualTo("partial");
        assertThat(count("artifact")).as("7 of 9 parts").isEqualTo(7);

        // Two findings: the orchestrator's own, plus ours for the partial status.
        assertThat(jdbc.queryForList(
                "select severity from autwit.finding where session_id = ?", String.class, sessionId))
                .hasSize(2)
                .allSatisfy(s -> assertThat(s).isEqualTo("medium"));
    }

    @Test
    void anOffScaleSeverityFromTheOrchestratorIsNormalisedRatherThanDropped() {
        // invoke_partial.json sends severity "warn", exactly as SKILL_CONTRACT §5's
        // wording invites -- but warn is a Verdict, not a Severity, and the DB's
        // finding_severity_check rejects it. Without normalisation this run dies on a
        // constraint violation, turning a documented condition into a hard failure.
        // See CONTRACT_RATIFICATION_REQUEST.md Q4.
        enqueuer.enqueueMilestone(sessionId, "partial_capture", List.of("order_flow"), true, null, null);
        worker.pollOnce();

        assertThat(jdbc.queryForList(
                "select message from autwit.finding where session_id = ? and part_key = 'shipment.legs'",
                String.class, sessionId))
                .as("the orchestrator's warn finding survives, relabelled -- evidence is never dropped")
                .singleElement(org.assertj.core.api.InstanceOfAssertFactories.STRING)
                .contains("shipment_pg unreachable");
    }

    @Test
    void anOrchestratorFailureMarksTheRunFailedNotTimedOut() {
        var accepted = enqueuer.enqueueMessage(sessionId, "this will fail", null, null, null);
        worker.pollOnce();

        var run = runs.find(accepted.run().runId()).orElseThrow();
        assertThat(run.status()).isEqualTo("failed");
        assertThat(run.error()).containsEntry("code", "upstream_unavailable");
        // retryable is advisory -- we record it, we never act on it for an invoke run.
        assertThat(run.error()).containsEntry("retryable", true);
        assertThat(run.attempts()).as("still never auto-retried").isEqualTo(1);
    }

    @Test
    void aSecondSnapshotUsesIdenticalPartKeys() {
        enqueuer.enqueueMessage(sessionId, "I created order XXXX", null, null, null);
        worker.pollOnce();
        enqueuer.enqueueMessage(sessionId, "I fulfilled the order", null, null, null);
        worker.pollOnce();

        var byShot = jdbc.queryForList("""
                select s.label, count(*) as parts,
                       string_agg(sp.part_key, ',' order by sp.part_key) as keys
                from autwit.snapshot s join autwit.snapshot_part sp on sp.snapshot_id = s.snapshot_id
                where s.session_id = ? group by s.snapshot_id, s.label
                """, sessionId);

        assertThat(byShot).hasSize(2);
        // The single most important field in the contract: if these ever diverge, the
        // diff engine reports phantom added/removed parts instead of a real diff.
        assertThat(byShot.get(0).get("keys")).isEqualTo(byShot.get(1).get("keys"));
    }

    private int count(String table) {
        return jdbc.queryForObject(
                "select count(*) from autwit.%s where session_id = ?".formatted(table), Integer.class, sessionId);
    }
}
